[package]
name = "gaodaoyi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = { version = "0.25.5", default-features = false, features = ["png", "jpeg"] }
inquire = { git = "https://github.com/mikaelmello/inquire", rev = "3cd5d7a" }
viuer = "0.9.1"

[workspace]
members = [
    "epub2html",
    "html2json"
]
