[package]
name = "html2json"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.22"
anyhow = "1.0.95"
serde_json = "1.0.134"
serde = { version = "1.0.217", features = ["derive"] }
clap = { version = "4.5.23", features = ["derive"] }
regex = "1.11.1"
glob = "0.3.2"
